# ampm build configuration
#
# A ``config.toml`` must live in your build directory.
# Paths can be relative or absolute.
 
[paths]
source    = '[3] Export Packets'
stl       = 'JR299_fullplate.stl'
parts_csv = 'JR299_sterling_parts.csv'
 
[build]
layer_thickness = 0.03  # mm
 